version: '3'

services:
  # Django app
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=movie_db
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=root

  # MySQL database
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movie_db
    ports:
      - "3306:3306"
